// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMqcqaRKhMJLaMv8ONieiEzK-U8oGt3Zc',
    appId: '1:521257840139:android:6e182fdccb8676f6dd210e',
    messagingSenderId: '521257840139',
    projectId: 'chat-app-9f719',
    databaseURL: 'https://chat-app-9f719-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-9f719.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChl20GJGMNTABEZDwvtIgsJWYoD9V7_RI',
    appId: '1:521257840139:ios:b29a7e49a78fef57dd210e',
    messagingSenderId: '521257840139',
    projectId: 'chat-app-9f719',
    databaseURL: 'https://chat-app-9f719-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-9f719.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
